# Multi-stage Dockerfile optimized for Node.js and Next.js
# Production-ready with minimal image size

# Stage 1: Dependencies
FROM node:24-alpine AS deps
WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install

# Stage 2: Builder
FROM node:24-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set environment to production
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Client-side Firebase env vars (NEXT_PUBLIC_* are embedded at build time)
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Dummy env vars for build time (real values provided at runtime)
# Note: These are placeholder values - the private key is a dummy that parses but has no real value
ENV FIREBASE_PROJECT_ID=placeholder
ENV FIREBASE_CLIENT_EMAIL=placeholder@placeholder.iam.gserviceaccount.com
ENV FIREBASE_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA0Z3VS5JJcds3xfn/ygWyF8PbnGy0AHB7MmE9kFYkJlGFRhpr\npA1nRtbxPOq4GxKaRPGqM5k+H8nZQQH0B0pJnDQ9Ry1yvQSNPvPLM5pLvosMNmhP\nCSAZIoi9hQKzhyMBykfLz6GvvMvqhz6M0rxq8LAUP0xkGlzX0HPJb7jLLBdvmJQ1\nz5lXOWWFrwkDNfPmfPBJVPGjF3jFsG4Q8vcLsrhB1M4jPcwLMnOPnlLMQfSL3b1G\nCjZvPFCbmJGiPLKkY3l5R4pUGFLvTNmJQRmnxjNY8jvLoMYx6RqVsRqnhB4QdNlp\nNKMsqCwvLVHigQJcSB5JKYWwPjqNPnTmF7MBQQIDAQABAoIBAC5RgZ+hBx7xHnFZ\nnQmY4glnqHBPwbDW4T0fLRa4QqfXJbQ2jCjcZwKU+R1kN8N3A7gE0QaGz7Y4ADHU\nBQFEEhjKrFQ1m+OMmKvGnDB8dDNQPfLmNQE9HlKvPYAktBqtDiJlmbyjpHs6MLsP\nEpDpUQz7orfHvBx3vM2TwDqLRMqZp+WxPLnOdLmM8wEdCdNBryG4sXko8V1mGbFD\nfKq4iFJNOgfQpCKaPgxiJZBldB1sjxzCZNCvGJMb1yfQgtmC0QL+s9GWNZ4SQMH/\nCfpKlIcMnLd0lPmL7hJKKSrWPwn5Rpl/qLMLBkvkJJKlsME0+xAKmcMQqE1ycJpQ\nvTVWmJECgYEA7+VwDPT85qJLY5o0CIBUQ1Jcn+fPHUNLpkmZkzfTHcG5bnHvLQXb\nlsyW0vZdf0KQHpJl9JgPFQZjsZPQnOLAuoTq9JfHPxQGzPvYL2fOBBr9O7WPfPC1\nBNg7dqXPmPggmiRlCIZLoIuMMce9QQFMgXfr0qjPfXnETvVMjMNYaJUCgYEA3j7g\n2Q6FLhlbPY7vp2bQq2aO3mTEvJwzGLXchPKqRm7M4GmzCJh+xLBJir9EPE1TcnPT\njpE6L9n2Z1ePWPYMUgNvLQE8VLfBgj5R9Jd3EmZvlnGBBb6pdjrT8Nq1a3XRFY+j\nmYxPP7lPJnEa1ysXYnYsqPqNSHfnLlRMzlWHvl0CgYEA1Ht8LtLBCwPJixgN5gdQ\nx1n7X8UC6c7xI3D4OlRUwm1lPPJIPpLnBeUr/FWsdaS3C5TST7K3wLbMZ4jBOyTO\nJKY3v/rFjDBASgh5J1XLqYGaLY5PTb+whC9lMb2bR4oTunFnuoJLqCiQti8iMV0R\nV7WqEMZnm2QmOMgpUJZS6rECgYEAx6dO8X1vWboSHh8y2cNjL7GKBLSaRG1HZHUy\nJG8XPvvHHdjGjPvKhBzP8fOMByaYBzA8jIxDVIc8P8fy+bXqhJiqHw7z7WAgZkIx\npKNQ7JRPY8pvJPtLKPNGLdFUO0OB6J6g6xoAoxQnkOFJgbsuu7oLRj5lMCx/hCOR\n6xTPVkkCgYBQ9y3tF5qp7i6KQ2fBjPpcg1H4E7SkCGOL6uwbeskJJGMsHd8QRMBQ\nFOG+wHc/7pfPQm3JkAVZONYL5Gb8c+J6bGLpEIAFQ1R7ZwqwDBPJkCkjjJaYnL8K\noF5W2S5kGLfzEh8v7q2CyisI6NzJ3ohH2d0j/6TcTnb6w1hOJEpALA==\n-----END RSA PRIVATE KEY-----"
ENV FIREBASE_STORAGE_BUCKET=placeholder.appspot.com

# Auth Firebase env vars (used by NextAuth FirestoreAdapter)
ENV AUTH_FIREBASE_PROJECT_ID=placeholder
ENV AUTH_FIREBASE_CLIENT_EMAIL=placeholder@placeholder.iam.gserviceaccount.com
ENV AUTH_FIREBASE_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA0Z3VS5JJcds3xfn/ygWyF8PbnGy0AHB7MmE9kFYkJlGFRhpr\npA1nRtbxPOq4GxKaRPGqM5k+H8nZQQH0B0pJnDQ9Ry1yvQSNPvPLM5pLvosMNmhP\nCSAZIoi9hQKzhyMBykfLz6GvvMvqhz6M0rxq8LAUP0xkGlzX0HPJb7jLLBdvmJQ1\nz5lXOWWFrwkDNfPmfPBJVPGjF3jFsG4Q8vcLsrhB1M4jPcwLMnOPnlLMQfSL3b1G\nCjZvPFCbmJGiPLKkY3l5R4pUGFLvTNmJQRmnxjNY8jvLoMYx6RqVsRqnhB4QdNlp\nNKMsqCwvLVHigQJcSB5JKYWwPjqNPnTmF7MBQQIDAQABAoIBAC5RgZ+hBx7xHnFZ\nnQmY4glnqHBPwbDW4T0fLRa4QqfXJbQ2jCjcZwKU+R1kN8N3A7gE0QaGz7Y4ADHU\nBQFEEhjKrFQ1m+OMmKvGnDB8dDNQPfLmNQE9HlKvPYAktBqtDiJlmbyjpHs6MLsP\nEpDpUQz7orfHvBx3vM2TwDqLRMqZp+WxPLnOdLmM8wEdCdNBryG4sXko8V1mGbFD\nfKq4iFJNOgfQpCKaPgxiJZBldB1sjxzCZNCvGJMb1yfQgtmC0QL+s9GWNZ4SQMH/\nCfpKlIcMnLd0lPmL7hJKKSrWPwn5Rpl/qLMLBkvkJJKlsME0+xAKmcMQqE1ycJpQ\nvTVWmJECgYEA7+VwDPT85qJLY5o0CIBUQ1Jcn+fPHUNLpkmZkzfTHcG5bnHvLQXb\nlsyW0vZdf0KQHpJl9JgPFQZjsZPQnOLAuoTq9JfHPxQGzPvYL2fOBBr9O7WPfPC1\nBNg7dqXPmPggmiRlCIZLoIuMMce9QQFMgXfr0qjPfXnETvVMjMNYaJUCgYEA3j7g\n2Q6FLhlbPY7vp2bQq2aO3mTEvJwzGLXchPKqRm7M4GmzCJh+xLBJir9EPE1TcnPT\njpE6L9n2Z1ePWPYMUgNvLQE8VLfBgj5R9Jd3EmZvlnGBBb6pdjrT8Nq1a3XRFY+j\nmYxPP7lPJnEa1ysXYnYsqPqNSHfnLlRMzlWHvl0CgYEA1Ht8LtLBCwPJixgN5gdQ\nx1n7X8UC6c7xI3D4OlRUwm1lPPJIPpLnBeUr/FWsdaS3C5TST7K3wLbMZ4jBOyTO\nJKY3v/rFjDBASgh5J1XLqYGaLY5PTb+whC9lMb2bR4oTunFnuoJLqCiQti8iMV0R\nV7WqEMZnm2QmOMgpUJZS6rECgYEAx6dO8X1vWboSHh8y2cNjL7GKBLSaRG1HZHUy\nJG8XPvvHHdjGjPvKhBzP8fOMByaYBzA8jIxDVIc8P8fy+bXqhJiqHw7z7WAgZkIx\npKNQ7JRPY8pvJPtLKPNGLdFUO0OB6J6g6xoAoxQnkOFJgbsuu7oLRj5lMCx/hCOR\n6xTPVkkCgYBQ9y3tF5qp7i6KQ2fBjPpcg1H4E7SkCGOL6uwbeskJJGMsHd8QRMBQ\nFOG+wHc/7pfPQm3JkAVZONYL5Gb8c+J6bGLpEIAFQ1R7ZwqwDBPJkCkjjJaYnL8K\noF5W2S5kGLfzEh8v7q2CyisI6NzJ3ohH2d0j/6TcTnb6w1hOJEpALA==\n-----END RSA PRIVATE KEY-----"

# Build the application
RUN npm run build

# Stage 3: Runner (Production)
FROM node:24-alpine AS runner
WORKDIR /app

# Set environment
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set correct permissions
RUN chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port
EXPOSE 3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "fetch('http://localhost:3000/api/health').catch(() => process.exit(1))"

# Start the application
CMD ["node", "server.js"]
